### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by m1ga** [atom-minimap/minimap#239]
Is it possible to make the background transparent, so you can see how long the line is below the map

**Comment by fundon** [comment]
Maybe it's a option.

**Comment by abe33** [comment]
I think this is something that should be resoved through CSS rather than with an option, the new v4 version is using the flex layout of the editor to position itself properly. To achieve what you ask it's necessary to make the minimap out of the flow (position: absolute) so that the editor can flow below it.
But this can be true only when the minimap is displayed on the right.

**Comment by m1ga** [comment]
ah ok, so its not an overlay its a new pane on the right side.

**Comment by abe33** [comment]
Exactly, the v3 was behaving like an overlay, but it was clearly suboptimal given that the default behavior users were expecting was that the editor doesn't flow below the minimap.

**Comment by abe33** [comment]
Closing it for now as there's no real solution for that.

**Comment by DavidAwad** [comment]
What if we just set a `z-index : -1`  for the minimap?

**Comment by DavidAwad** [comment]
Tried it, didn't work as simply as I'd hoped : (
