### ISSUE TITLE
Satus Bar Causes Height Bounce

### ISSUE THREAD

**Issue by robneu** [atom-minimap/minimap#295]
I have the Atom Linter set to show notifications in the status bar and whenever one is generated it causes a height bounce in the minimap. It's distracting enough that I've disabled the package for right now, so I figured I should probably open an issue about it. Here's a Gif that shows the issue:

![notify](https://cloud.githubusercontent.com/assets/2184093/6584119/008d3fb2-c737-11e4-9c13-06dc7863d2dd.gif)

**Comment by abe33** [comment]
I see... but I wonder if there is a solution to that problem. 

Let me explain a bit how the minimap works in that situation. 

We have here a really long buffer, which doesn't fit in the minimap as a whole, so we have to scroll through the minimap content to display the part we're interested in, the section that cover the visible part of the buffer. So we compute the minimap scroll top value using the editor scroll top and the minimap height. When the minimap is resized the scroll top value is computed again to fit the new size, so the minimap scroll top value also changes, resulting in the jump you can witness. You can also witness that behavior when you open the devtools or the find and replace panel.

The scroll top value is computed so that the motion of the visible area goes from the top edge to the bottom edge along the course of the editor scroll. When you reach the bottom of your file, the visible area in the minimap hit the bottom of its scrolling track. Then preventing the jump by keeping the same scroll will mess up the whole logic. 

Note that the Sublime Text's one behave exactly like that too.

A possible solution for you would be to tweak the styles of the status bar so that it doesn't affect the flex box flow, by using a `position: absolute` on the status bar for instance.

**Comment by robneu** [comment]
That makes sense. I figured a CSS solution would probably be the best route.

It looks like the only sensible way to target it is to set the entire bottom panel to `position:absolute`. I'm not sure if that will cause issue with other packages, but I'll give it a go.

**Comment by robneu** [comment]
For anyone else who runs into this, adding this to your stylesheet seems to work pretty well. It might cause display problems with some packages that I'm not using, but so far so good on my end. :)

``` less
.workspace {
    > .bottom {
        bottom: 0;
        position: absolute;
        width: 100%;
    }
}
```

**Comment by abe33** [comment]
Great to hear a CSS tweak fixed things for you. I guess I can close this issue then.
