### ISSUE TITLE
Add support for linter-error class

### ISSUE THREAD

**Issue by vilic** [atom-minimap/minimap#323]
It would be nice if minimap has built-in support for that~ Thanks for your great work! :v:

**Comment by abe33** [comment]
Thanks for the suggestion, there's no chance that it become a built-in support but it'll be a good plugin. 
We're trying to avoid having too much things in the minimap and prefer having plugins to handle all the features that relies on other packages API (git diff, find and replace, etc.).

In fact I've started writing a plugin for that but got stuck because the linter package doesn't expose anything that we can use to access linters results. So I'm still waiting for the linter package to expose a service so that we can get informations from it.
