### ISSUE TITLE
Optimize load time

### ISSUE THREAD

**Issue by zimme** [atom-minimap/minimap#325]
Please look into using `activationCommands` in `package.json` to make the package activate only once it's toggled

**Comment by abe33** [comment]
It's not really possible, as most people expect the minimap to be present from startup for all editors we can't rely on an activation command because it removes completely all ability to act on startup.

Maybe we can still gain a few ms by being even more lazy when registering the custom element to the model by delaying it to the moment a minimap really needs to be created (on the command is disable auto-toggle).

**Comment by zimme** [comment]
Fair enough, I just wanna get my load time down as much as possible. I've opened an issue about this for pretty much all packages I use.

What if the activation command is the toggle command, wouldn't that make minimap load once it's shown the first time?

**Comment by abe33** [comment]
The thing is that activation commands have to be triggered by the user, so you can't have an activation command triggered programmatically at package's load time. 
There's also the issue that a package config isn't known before it gets activated, the file is not even required as the activation command is defined in `package.json` so we can't just run some code in the main file to look for the auto-toggle , disregarding the package activation for that. And doing so would be bad because we would introduce side effects on other package loading, as well not honoring the life cycle interface of a package: the main file would actually change the state of the app even when the package isn't activated.

**Comment by zimme** [comment]
Ok. I'll close this then as load time optimization by activationCommands isn't an option.
