### ISSUE TITLE
Minimap isn't available when opening a file using 'sudo'

### ISSUE THREAD

**Issue by IvanMaldonado** [atom-minimap/minimap#388]
I'm using Atom to change some stuff for the LMMS stylesheet, I installed the minimap which works great when opening a regular file, but as soon as I open the LMMS's .css file, the minimap isn't there anymore and it is not into the Packages menu.

<img src="http://imgur.com/GhuQCG2.png" />
</a>
<img src="http://imgur.com/XNVBTT2l.png" />
</a>

**Comment by abe33** [comment]
Hmm, not sure to understand what it has to do with the minimap itself. Do you have any message in the console? Is there any other packages that are not available when ran with sudo?

**Comment by olmokramer** [comment]
Atom installs (and looks for) packages to the user's `~/.atom/packages`. Because you start Atom as root it will look for packages in `/root/.atom/packages` and doesn't find anything. You can set the `ATOM_HOME` environment variable for `sudo` to point to your `/home/username/.atom` directory to instruct Atom to look there for its configuration files and packages.

**Comment by abe33** [comment]
Ok, I'm closing it since it's not related to the minimap.

**Comment by IvanMaldonado** [comment]
@olmokramer This helped me, thank you!
