### ISSUE TITLE
Minimap is blank in the middle of files

### ISSUE THREAD

**Issue by JestonBlu** [atom-minimap/minimap#413]
I saw this issue was addressed earlier this year, but its appearing on my setup when I have really long scripts. This one is about 2000 lines.  If I scroll from the bottom to the top of the script it renders correctly, but scrolling top to bottom displays gaps . My setup is on Windows 7.

![gaps](https://cloud.githubusercontent.com/assets/3339909/11188886/b72bd374-8c52-11e5-8527-063f6c0e2980.png)

**Comment by abe33** [comment]
And what's your setup exactly? (Atom version, minimap version, etc.)

**Comment by JestonBlu** [comment]
Atom 1.2
Minimap 4.16
Windows 7

**Comment by abe33** [comment]
Hmm, weird, I'll have to check if I can reproduce this on my windows computer. Stay tuned.

**Comment by tamas821** [comment]
Hi!
I am experiencing the same issue on my desktop computer, however the problem exists for me even when scrolling downwards. If I stop scrolling and enter a character into the text, the minimap showing the parts below that show up correctly again. Atom 1.2.1, Minimap 4.16.0, Windows 7. 
I have no issues on my surface pro 3 with same software and win10.
Not sure if it matters: my screen resolution is 1920x1080

![minimap_issue](https://cloud.githubusercontent.com/assets/15919230/11262577/52582172-8ec4-11e5-83dd-e5773ed960ad.jpg)

**Comment by abe33** [comment]
Hi folks, I could try on windows yesterday and couldn't reproduce it. Do you happen to see which circonstances could lead to this issue? I mean is it happening on all files long enough to make the minimap scroll, or is there some other conditions to fulfill to trigger that issue? 
Also, could you tell me what is the value of `devicePixelRatio` within Atom? (open the devtools and use the console for that)

**Comment by JestonBlu** [comment]
It appears to be happening for me on any file that requires minimap to scroll. My devicePixelRatio returns 1.

**Comment by tamas821** [comment]
Same here, the problem seems to appear for all files long enough for scrolling. I'll check the devicePixelRatio on Tuesday when I get to work.

**Comment by tamas821** [comment]
Hi. My devicePixelRatio is 1.

**Comment by abe33** [comment]
That's going to be hard for me to find a fix if I can't reproduce that on my own computers (how to make sure a fix works in these conditions?). 

I'll try to find a device on which I can reproduce the issue, but until then, if one of you (or someone else that also have this issue) want to give it a try it would really help me. I'll try to make a longer comment with possible hypotheses and where to look in the code so that you don't have to waste time looking around.

**Comment by SunsetOrange** [comment]
I've been having a similar issue. The minimap fails to fully update its view when code folding.
When I fold to different levels with Ctrl-k + 0,1,2,etc; the minimap seems to fail to draw the entirety of the map space. The bug is very reproducible. Latest atom and minimap versions as of half hour ago.

![01](https://cloud.githubusercontent.com/assets/7814343/11831091/13282220-a3f7-11e5-823b-f32ab56fa8cb.PNG)

![00](https://cloud.githubusercontent.com/assets/7814343/11831093/132d2acc-a3f7-11e5-8d6f-cd0073aec0d2.PNG)

![02](https://cloud.githubusercontent.com/assets/7814343/11831092/132c426a-a3f7-11e5-9a8b-d5571bf7f898.PNG)

**Comment by abe33** [comment]
@SunsetOrange It rather looks like #429 for me? Does 4.18.1 improve things for you?

**Comment by SunsetOrange** [comment]
Ah I was looking for an existing thread on this issue, but couldn't find one.
The x.xx.1 update does fix the issue thanks.

**Comment by fundon** [comment]
Thank you for your feedback. Some problems are the same as https://github.com/atom-minimap/minimap/issues/367.
Closed.

**Comment by tamas821** [comment]
I am suggesting to reopen this issue, because:
On my Surface Pro 3 + win10 machine I had minimap blurring problem (but no "minimap becoming blank in middle of files when scrolling" problem), which dissapeared after some update. On my win7 desktop pc I didn't have blurring problem, but had and still have "minimap becoming blank in middle of files when scrolling" problem with latest atom + minimap updates (1.3.1 and 4.18.4).

**Comment by abe33** [comment]
@tamas821 Do you feel confident to try a few things for us? As I said, unfortunately I'm in no position to debug what happens as I still have to find a windows device where I get this bug.

**Comment by tamas821** [comment]
@abe33 I am quite a newbie to js and have zero experience with coffeescript, but I can certainly follow instructions or experiment with stuff if you provide some guidance. I would be happy to help if I can. :)

**Comment by duke9509** [comment]
I can't speak to what might be happening on Windows, but I just switched to using Atom on OSX, installed this plugin and am getting this issue with the following behavior:
With the OSX momentum-based smooth scrolling, the blank areas appear at the bottom of the minimap when scrolling slower than max speed. So, under normal scrolling circumstances, this corresponds to the pauses in finger movement on the touchpad.
If I purposefully scroll very slowly, then I can get it to be almost completely blank.
This does not work when scrolling up.

**Comment by faabiopontes** [comment]
I have Windows 7 64x.

The problem seems to be on "minimap scroll" that happens when files have more than 298 lines.
I made a file with 298 lines. No problem.
But when the file has 300 lines, there is the bug.
![img3](https://cloud.githubusercontent.com/assets/2223935/14461659/eae234a4-0099-11e6-9e2b-5d201887df47.png)

I went down on the file using Page Down and Page Up, but it also happens when i scroll with mouse whell, holding the mouse on the scroll, clicking the minimap, pressing down or up, or using Go To Line.

With more lines it bugs almost half of the minimap.
![img3](https://cloud.githubusercontent.com/assets/2223935/14461742/3e4933d6-009a-11e6-8821-2301638c6d5a.png)

When I go up the minimap begins to show the lines again.
![img3](https://cloud.githubusercontent.com/assets/2223935/14461775/69320ea6-009a-11e6-8ef5-d868c7190ab2.png)

Hope it helps, tell me if I can do anything.

**Comment by faabiopontes** [comment]
Solved updating to 4.23.2

**Comment by tamas821** [comment]
Unfortunately the 4.23.2 update didn't solve the issue in my case.
Here is some additional information which might be useful:
When scrolling down from the top of a file (which is long enough for minimap to need scrolling), the point where the minimap starts to get blank depends on the screen resolution.
On my left monitor:
With 1920x1080 resolution it starts from around 428 pixels below the top of minimap.
With 1600x900 resolution it starts from around 252 pixels below the top of minimap.
With 1280x720 resolution the problem is completely gone.

On my right monitor:
With 1680x1050 resolution it starts from around 444 pixels below the top of minimap.
With 1280x800 resolution it starts from around 204 pixels below the top of minimap.
With 800x600 resolution the problem is completely gone.

The pixel numbers at which the blanking appears seem to be independent of the minimap settings on how many pixels the letters and the space between lines are.

I hope this info helped.
Cheers

**Comment by faabiopontes** [comment]
Didn't solve here as well. I don't know what happen.

I did some testing with the information of resolutions.

With 800 height (like 1280x800) the problem is gone. But if the height is higher than 800 the problem comes back.

My normal resolution is 1650x1050, if I split the two files vertically on Atom when one of the panels are higher than 500px the bug starts to show up again.

Problem appearing at top panel.
![image](https://cloud.githubusercontent.com/assets/2223935/14916761/d68797f0-0df1-11e6-83c2-6ba161051019.png)

Problem appearing at bottom panel
![Uploading image.png…]()

**Comment by sweetppro** [comment]
This bug seems to be theme dependant. It happens for me when I use the Genesis Syntax Theme but not for other themes.

**Comment by duke9509** [comment]
I also use Genesis. Switching to Atom Dark also fixes the problem for me.

**Comment by tamas821** [comment]
I use One Dark theme and switching to Atom Dark doesn't help.

**Comment by JestonBlu** [comment]
I swapped out several themes and syntax highlighting options (light and dark) and it doesn't seem to make a difference on my setup.  

My Settings:
OS: Windows 7 Prof
Screen Resolution: 1920x1080
Atom: 1.7.4
Minimap: 4.24.3
UI Theme: Northern Dark Atom
Syntax Theme: An Old Hope

**Comment by abe33** [comment]
Hi there, despite my efforts to find a device onto which I can reproduce that issue, I still don't have one that I can use. 
If anyone feel to take a look at that I may be able to provide some help on where looking for an issue and where to log things to figure what can go wrong here.

**Comment by scoady2** [comment]
I also have this issue and have reproduced it on 2 separate dev devices. Both mac 10.11.5 and atom 1.8.0 and minimap 4.24.7. when i have genesis syntax turned on parts of my code in minimap disappears. the theme itself seems to be fine and when i change syntax to one dark or whatever the issue stops. have only tested 6 or 7 syntax but genesis is the only one causing an issue for me on both laptops

**Comment by dwelle** [comment]
For me the issue happens for both `one dark` and `atom dark` themes. Win 7 x64, Atom 1.10.2, minimap 4.25.

**Comment by dwelle** [comment]
If you still encounter this issue, check if `--disable-gpu` flag doesn't solve it: https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem

**Comment by JestonBlu** [comment]
I don't see this happening anymore. Not sure if others are still experiencing it. From my perspective this can be closed.
