### ISSUE TITLE
Refactor with ES6 (ES2015)?

### ISSUE THREAD

**Issue by fundon** [atom-minimap/minimap#416]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Looks like GitHub (including <a href="https://twitter.com/AtomEditor">@AtomEditor</a>) is finally dumping CoffeeScript in favor of ES2015 (using <a href="https://twitter.com/babeljs">@babeljs</a>). <a href="https://t.co/JeS2f0pYFv">pic.twitter.com/JeS2f0pYFv</a></p>&mdash; Sindre Sorhus (@sindresorhus) <a href="https://twitter.com/sindresorhus/status/669958889941639168">November 26, 2015</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
cc @abe33

**Comment by abe33** [comment]
Yeah, I saw that. 

I'll be a bit wary of this kind of "announcement" based on the comment of one guy on an issue thread. The thing have been discussed a lot among maintainers, but it's no small feat so I guess Atom won't be in ES6 before long.

Also, I actually started to migrate the minimap, but sadly decaffeinate doesn't really help and the task is just too painful so I put a hold on it until I find a better way to make the conversion.

**Comment by fundon** [comment]
Yes, it's very painful 😂 and it's also too feat.


> Also, I actually started to migrate the minimap

Great work.

We can create a todo list for this change, and assign some tasks to me 😄 .

**Comment by abe33** [comment]
Yeah, at least I need to publish the branch.

The really tricky part is that we should either not touch the specs or migrate the specs first. Because we can't just assume will be able to convert everything to es6 without breaking something at some point. And if we start working on both will risk to mess up some tests without noticing.

There's also the problem of the documentation. I switched to esdocs on my es6 branch, it gives great results, but that means that every single comment blocks must be updated. Which add to the complexity of the conversion (we can't just keep the previous API docs pointing to the coffee sources).

Lastly, there's a even bigger work in term of refactoring to make the code as pretty in ES6 as it was in Coffee. As machiste in the toggle quote PR I use `standard` rather than `eslint`. But there's still a lot of ugly things when converting directly from decaffeinate.

As for the workflow I use: 

1. I started with small classes (the mixins) and convert one making sure the specs are still green.
2. If there's specific specs for the mixin I convert them, making sure they're still green once converted
3. Rince and repeat

I won't touch to core classes like `Minimap` and `MinimapElement` until I'm confident that the move can be done quickly.

**Comment by abe33** [comment]
Some bad news:

Just converting the canvas drawer mixin to babel gives awful results

Here's the initial timeline while typing on dev mode with the coffeescript version: 
![drawer-coffee](https://cloud.githubusercontent.com/assets/247140/11543835/1f94c29c-993f-11e5-83b7-3fcd07ddc622.png)

Then here's the timeline when typing and using the converted version running through babel:
![drawer-babel](https://cloud.githubusercontent.com/assets/247140/11543831/1c9e4144-993f-11e5-822d-f1a731c2ac57.png)

There's clearly a problem here. I still don't know if it's because the way babel create classes or if it's something with the fact it's a mixin, or something else, but it won't be as simple as converting code to ES6.

**Comment by fundon** [comment]
Maybe we need  to first read [ECMAScript 2015 (ES6) in Node.js](https://nodejs.org/en/docs/es6/),
and just use pure ES6 codes without babel transformer.

Wow, 9x total time, too slower.

I think that pre-compile the code with the babel will be good way(No Babel Runtime).

**Comment by abe33** [comment]
>  just use pure ES6 codes without babel transformer.

Sadly we can't, we're dependent of Atom for that, we don't control the v8 flags nor the enabled babel transforms.

The good news is that the issue came from the way decaffeinate (CS redux) compiles for..in loops. Vanilla CS stores the array's length in the first statement of the loop while redux evaluate it on every iteration. The extra cost came from that. 
Also, by talking with nathan, it appears that ES6 for..of loops are a no-go too. V8 don't optimize them so they are the slowest kind of loop we can use (even a forEach is faster).

So for the moment, I'll go with the safest route, compiling using vanilla CS and then rewrite some parts to make it ES6 compliant.

**Comment by fundon** [comment]
> Sadly we can't, we're dependent of Atom for that, we don't control the v8 flags nor the enabled babel transforms.

Yeah, we don't control the v8 flags, but we could know that which flags are enabled in Atom.


> The good news is that the issue came from the way decaffeinate (CS redux) compiles for..in loops. Vanilla CS stores the array's length in the first statement of the loop while redux evaluate it on every iteration. The extra cost came from that.

Nice.



> So for the moment, I'll go with the safest route, compiling using vanilla CS and then rewrite some parts to make it ES6 compliant.

Yeah, right :+1: , we can refactor it start from some little parts.

BYT, Great works!

**Comment by fundon** [comment]
The Electron has used Node-v4.1.1 in v0.33.2.
https://github.com/atom/electron/releases/tag/v0.33.2
