### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by alexchandel** [atom-minimap/minimap#451]
This package adds 60ms to my startup time, compared to 37ms from `linter`, 4ms from `swackets`, 2ms from Sublime-Style-Column-Selection, and 0ms from everything else (`lines` and a few dozen languages). Get your `-O3 -flto` going, because that's way too slow.

**Comment by abe33** [comment]
You probably aren't really familiar with both concurrency and benchmarking, because, otherwise, you would know that a single measure is not a proof, that Atom has to load and activate things in parallel of other system tasks and that it can affect its performances.

**Comment by alexchandel** [comment]
@abe33 I am extremely familiar with both concurrency and benchmarking. And what you mistook for "rudeness" was humor, something evidently lost on you. I expected a forum to report this issue here, not snide defensive responses from someone who can't read tone. This is a real issue, and pretending it doesn't exist while feigning rudeness hypersensitivity doesn't fix it.

In my tests Atom routinely measures Minimap at anywhere between 60ms and 110ms. I chose the lower to err cautiously. Reopen.

**Comment by alexchandel** [comment]
@abe33 You may also want to read https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith, since that's what normal people use to meter their online interactions.

**Comment by abe33** [comment]
Sorry if I was rude myself, but humor isn't always perceivable on a post like that.  

>  I thought Get your -O3 -flto going was pretty damn funny too

Probably, if you know what it refers to, which is not my case.

>  I expected a forum to report an issue here, not snide defensive responses from someone who can't read tone and pretends issues don't exist

Sorry, but why do you assume that everybody here is able to "read tone"? 
Sure, for english native people it's seems easy, but maybe you should also consider that not everyone has the same english skills and references as you. 
In my case, your `Get your -O3 -flto going, because that's way too slow` isn't funny, it sounds more like `Y U NO OPTIMIZE?`, so yeah I didn't appreciate what I thought it implied.
And I don't pretend that there's no issue, only that without proper profiling and performances analysis the `it's too slow argument` is meaningless. And even with proper data, it's not like I can magically overcome every constraints of this specific package. There's always a trade-of between performances, features and code readability. 
You take the linter case, the linter can obviously defers a lot of its work until the point it has to lint something, which occurs either on typing or on save depending on the configuration you use. For the minimap, I have to display a minimap as soon as the editor is loaded, which mean I need to have the models, custom views and such initialized early, because I can't assume that there will never be any editor on screen when Atom is starting. 
Also, 60ms is a bit less than four frames in a browser (at 60fps), I think that's rather short, and should not be that much noticeable for most people. So yeah, I would say it's not that terrible and that making the minimap loads all its resource on activation would raise even more complaints from users as it means the minimap would popup after the editor its bound to, leading to some kind of flicker in the UI.

Also thanks for the wikipedia link, I didn't know about that, then let me also advice you a link: https://github.com/isaacs/github/issues/167
Not that I have the same amount of issues than other well-know/successful maintainers, but you have to understand that I'm maintaining the minimap and its packages all alone, that and many other Atom packages, and I have my work and personal life too. So I tend to be less and less patient when it comes to issues that looks like blunt complaints without regards to the maintainers works.

**Comment by alexchandel** [comment]
[-O3 -flto](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html). That's a great link, and I can sympathize with the burdens of triaging open-source projects. I intended this issue to be less of a complaint and more of a medium-term tracking issue for reducing startup time, though it may not have been worded perfectly.

**Comment by abe33** [comment]
Ok, I see, sorry for the fuss. I'll reopen the issue, even if I'm not sure to see what ground breaking optimization will be available in our case.

**Comment by alexchandel** [comment]
When I was looking at one language package/code completer with a mysteriously long startup time, it turned out to be a single dependency that was doing blocking work on `require`. Fixing the upstream bug brought it from ~130ms to ~20ms.

**Comment by amilajack** [comment]
I'm experiencing the same issue but first, @abe33, I'd like to thank you for taking the time to create and maintain this package! Your contributions don't go unnoticed! Keep up the good work.

About the startup perf: what do you think about delaying the startup of this package so that the editor can startup? Similar to what `setTimeout` does with rendering?

**Comment by aminya** [comment]
Good news: I got access to minimap. I am adding all the performance patches I added to minimap-plus to minimap. So, this is/will be fixed.
