### ISSUE TITLE
Bug: Plugins don't activate when "Display Plugin Controls" is unchecked

### ISSUE THREAD

**Issue by dkerzig** [atom-minimap/minimap#458]
Hey,
I've used Atom for quite a while now and wanted to try the minimap-plugin. I've unchecked "_Display Plugin Controls_" because I like everything to be as minimalistic as possible. Then I've tried to install several plugins to extend the functionality of minimap:

- minimap-find-and-replace
- minimap-hide
- minimap-linter

The installation of all of them finished successfully and I even restarted Atom but none of them worked. So it took some time but I figured out how to solve the problem:

1.  Enable "Display Plugin Controls" in minimaps-settings & restart Atom -> Plugin works as expected now
2. Now you can disable "Display Plugin Controls" again & restart Atom and the plugin will continue to work as expected but without the settings-icon on hover.

This is reproducable and I have to do it for every new plugin :/ Hopefully you can figure out what is wrong with that or maybe we can figure out together if my configuration causes the problem in some way.

Dennis

**Comment by abe33** [comment]
Hi @dkerzig, thanks for the report, I clearly overlooked that case in the tests, this will be fixed with the next version. 

The main issue is that when the setting is turned on, plugins activation routine creates a setting for it with `true` as the default value, and the minimap plugins manager was expecting it when determining whether to activate a plugin or not. The proper behavior would be for the minimap to ignore the plugin's activation setting when `Display Plugin Controls` is turned off, and systematically activate the plugin.
