### ISSUE TITLE
Support for the overview of whole file without scrolling

### ISSUE THREAD

**Issue by perphyyoung** [atom-minimap/minimap#472]
When I open a file with much more lines, minimap may only show part of the full text(buffer limit?).
I wonder what is the boundary line count of minimap showing full text. Really hope to see more.
May I suggest that minimap set a toggle for overview the whole file, then minimap can work perfectly with **code glance**.

**Comment by abe33** [comment]
Hi @perphyyoung

> I wonder what is the boundary line count of minimap showing full text

There's no fixed boundary, it's a result of the rendering setting of the minimap. And in that regard the behaviour is roughly the same than the ST minimap.
Let's say the editor takes 1000px in height, and the minimap render a line with 3px height (2px for the chars and 1px between the line), only 1000/3 lines can be displayed in the available space. That's also why the minimap will scroll in sync when you scroll in the buffer. 

> May I suggest that minimap set a toggle for overview the whole file, then minimap can work perfectly with code glance.

Except that there's several issues doing so, let say I open a 100k+ file, still with an editor of 1000px height. 
Each line in the minimap, even without spacing between them, must be rendered at 0.01px, but canvas subpixel rendering cannot be accurate at these scales so end result would be a big blurry block. Colors would be mixed and probably unrecognizable. 
OTOH, mouse events only returns integer positions, so that means that even if the goal is to make code glance works with no regard to the minimap look, codeglance would jump 100 lines for each pixel of the mouse without any possibility to get between them.

The real fix here is that codeglance shouldn't set the text editor scroll when hovering over the minimap so that it doesn't reset the minimap position when you scroll in the minimap.
