### ISSUE TITLE
Slow Atom with minimap on

### ISSUE THREAD

**Issue by victorhguillen** [atom-minimap/minimap#475]
I confirm of all the plugins I deactivate, it was minimap who makes Atom slower, even when you change tabs was slow, I just Toggle minimap on/off and everything goes fast again.

Just confirm is this is a bug please. Thanks.

**Comment by abe33** [comment]
Hi @victorhguillen, 
Can you provide me with a [timeline record](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) and a [CPU profile](https://developers.google.com/web/tools/chrome-devtools/profile/rendering-tools/js-execution?hl=en) so that I can assert where the performance issue comes from? 

It'll be great if you could tell me more about your config, like providing the output of `atom --version` and `apm list`.

It may be related to the minimap, but it may be not necessarily something I can fix if the issue comes from a plugin I don't maintain or some other thing.

**Comment by victorhguillen** [comment]
Ok, I could determined it was another plugin, atom-css-class-checker, after I uninstall that plugin everything goes great, you can close the issue, thanks. @abe33
