### ISSUE TITLE
Minimap extremely thin on split pane

### ISSUE THREAD

**Issue by brycefranzen** [atom-minimap/minimap#497]
When I have two code pages split pane, the minimap is about 5px wide.  This problem goes away when I close the file and re-open it; however, as soon as I change the width of the screen again, the map shrinks.

**Comment by darianbr** [comment]
Same here. When I open the markdown preview in a split window the minimap is only a few px wide.

**Comment by abe33** [comment]
Hi there, would you be kind enough to provide me with a gif or a screenshot of the problem as well as information about your config? With my current setup I don't reproduce it.

**Comment by songsanli** [comment]
Same here. And I'll provide screenshots here to reproduce this bug:

Screenshot1: normal panel
![screen shot 2016-06-10 at 14 20 48](https://cloud.githubusercontent.com/assets/7044379/15955797/b2e73e04-2f16-11e6-9285-7c9dd52a308c.png)

Screenshot2: result of split right
![screen shot 2016-06-10 at 14 20 57](https://cloud.githubusercontent.com/assets/7044379/15955806/c3551266-2f16-11e6-9f2a-d8d63b84ea5c.png)

Screenshot3: relaunch Atom
![screen shot 2016-06-10 at 14 21 10](https://cloud.githubusercontent.com/assets/7044379/15955812/c9d69b3c-2f16-11e6-8c87-e8eec7cf0e12.png)

If you diff Screenshot2 and Screenshot3, you will find the minimap of left panel in Screenshot2 is wider than it in Screenshot3:

![minimap bug after panel split](https://cloud.githubusercontent.com/assets/7044379/15955979/d29afe88-2f17-11e6-8e5c-fd30e3fc5ebe.png)

So I think this bug is due to panel split.

**Comment by brycefranzen** [comment]
I have not been able to reproduce the issue yet.  I will send photos if it happens again.
