### ISSUE TITLE
julia-client notifications and the left side minimap conflict

### ISSUE THREAD

**Issue by dsweber2** [atom-minimap/minimap#519]
When using the minimap on the left side and running julia inline (as with shift-enter), the output of the notification isn't aligned with the end of the code as normal, making it impossible to read the code underneath it. I'm not entirely sure if the fix should be here or in the Julia client, so I've raised the issue in both.

screenshot of the behavior, see line 45 (or rather, don't which is the point):
![conflict](https://cloud.githubusercontent.com/assets/7095649/19217883/887a3862-8d9c-11e6-9c97-db34fc501ffc.png)

**Comment by abe33** [comment]
Hi @dsweber2, I'm not really sure what happens here, it looks like the julia client isn't using overlay decorations for these notifications (which should be the kind of decorations to use in that case). When using overlay decorations, they're placed in the editor so they aren't affected with the presence of the minimap. In that case it seems the notifcations are appended a level higher in the DOM tree and thus get affected by the minimap. I don't see any fixes on my end. But if you can lin to the issue you created on the julia client I may be able to provide some help on how solving that issue.

**Comment by pfitzseb** [comment]
[This](https://github.com/JunoLab/atom-ink/issues/79) is the issue on our side.

We are using `overlay` decorations, but those are placed directly inside the `atom-text-editor` element and therefore next to the `#shadow-root` which contains the minimap:
![overlayminimap](https://cloud.githubusercontent.com/assets/6735977/19391829/8608b9a0-922e-11e6-92b5-4d910b05c0b5.png)

So unless we're using overlay decorations wrong I'd argue this is an issue with either the decorations themselves or atom-minimap (because it would affect all overlay decorations, not only those from ink). Maybe you have some idea how to solve this?

**Comment by abe33** [comment]
Hi @pfitzseb, thanks for the explanation, and yes you're right, looks like something is wrong with how the minimap affects the overlay's offsets in that context. I'll try a few things, but we can already consider this is mostly an issue on my end.

**Comment by abe33** [comment]
Just published v4.25.3 that solves that issue. It's a bit of a dirty hack atm, I'll apply an offset to the overlays using the width of the minimap as margin-left. I'll think of a cleaner solution later.

**Comment by pfitzseb** [comment]
Thanks for looking into this!
This doesn't seem to work properly for me though -- I'm always getting the `10%` offset instead of the exact minimap width.
It does work with the following patch though:
```diff
  lib/minimap-element.js | 13 ++++---------
 1 file changed, 4 insertions(+), 9 deletions(-)

diff --git a/lib/minimap-element.js b/lib/minimap-element.js
index 7a8e315..e733f81 100644
--- a/lib/minimap-element.js
+++ b/lib/minimap-element.js
@@ -29,16 +29,11 @@ const updateOverlayStyle = (basis) => {
       overlayStyle.textContent = `
       atom-text-editor[with-minimap]::shadow atom-overlay,
       atom-text-editor[with-minimap] atom-overlay {
-        margin-left: ${basis};
+        margin-left: ${basis}px;
       }
       `
     } else {
-      overlayStyle.textContent = `
-      atom-text-editor[with-minimap]::shadow atom-overlay,
-      atom-text-editor[with-minimap] atom-overlay {
-        margin-left: 10%;
-      }
-      `
+      overlayStyle.textContent = ``
     }
   }
 }
@@ -1008,13 +1003,13 @@ export default class MinimapElement {
         }
       } else {
         delete this.flexBasis
-        updateOverlayStyle()
+        updateOverlayStyle(canvasWidth)
       }
 
       this.updateCanvasesSize(canvasWidth)
     } else {
       this.style.flexBasis = safeFlexBasis
-      updateOverlayStyle(safeFlexBasis)
+      updateOverlayStyle(canvasWidth)
     }
   }
```
IIUC the 10% offset won't ever work correctly because of the `fixed` property of the `atom-overlay`s, so it should be okay to remove it completly. We also need to update the margin in the case that theres no soft-wrapping-shenanigans (second to last diff). `safeFlexBasis` is also strange, but setting the offset to the minimap width works in that case too.

**Comment by abe33** [comment]
Hmm, weird, I thought I add tested it properly. Maybe it has to do with the fact that I'm running on Atom's master and that they removed the shadow DOM, I'll have to look at that on stable.

**Comment by pfitzseb** [comment]
Yeah, that seems likely. 
The issue seems fixed on the latest release (at least on Atom stable, Atom master doesn't really work for me). Thanks!

**Comment by dsweber2** [comment]
Thank you gentlemen for looking into this! Once I updated it seems to be working well. (incidentally, I also tried it with hydrogen, which also has no problem with the minimap).

**Comment by abe33** [comment]
Right, I forgot to post an update on this thread, the last release includes the patch from @pfitzseb. So yeah it should work now :)
