### ISSUE TITLE
minimap dosen't work

### ISSUE THREAD

**Issue by goo-dx** [atom-minimap/minimap#525]
I installed minimap(v4.26.1) in my atom but it didn't work, even after I click "toggle" (Packages-->Minimap-->Toggle). Something conflicting or inproper settings?  how can I get the log for this issue?
thanks for helping.
PS: my os is Windows 10 home edition

**Comment by goo-dx** [comment]
Disable and enable the package then restart atom can make it work. Issues #426 discuss the problem although it is weird.

**Comment by daniele-salvagni** [comment]
I have the same problem, I did try re-enabling/reinstalling but I can't get the minimap to work. This is showing up in the DOM when toggling but nothing is visible in Atom:

    <atom-text-editor-minimap><canvas></canvas><canvas></canvas><canvas></canvas>
        <div class="minimap-visible-area"></div>
        <div class="minimap-controls">
            <div class="minimap-scroll-indicator"></div>
            <div class="open-minimap-quick-settings"></div>
        </div>
    </atom-text-editor-minimap>

**Comment by abe33** [comment]
Hi there, which version of Atom are you running?

**Comment by abe33** [comment]
@daniele-salvagni And how did you install minimap to get version 4.26.1? It should not be available before Atom 1.13

**Comment by daniele-salvagni** [comment]
I installed it directly from Atom, I just uninstalled it to see if I can reproduce the bug and get this message:

![install](https://cloud.githubusercontent.com/assets/6751621/19720939/8535a434-9b70-11e6-89ce-12df18278e35.png)

And it does actually install that version. I remember getting the same message when I first installed it but I'm not sure if it stated 4.25.6, I didn't pay much attention, anyways I ended up with 4.26.1. This time actually installed 4.25.6 and minimap is working.

Before fixing it by using APM I did try to reinstall the package from Atom, that time I didn't get the message above and it did install 4.26.1 again.

**Comment by abe33** [comment]
Thanks @daniele-salvagni for the follow-up, I think there's definitely an issue in the settings view and how it deals with apm install. As I was the one who initially wrote the code that displays that message I'll see if I can find why it fails in some cases.

**Comment by daniele-salvagni** [comment]
I was able to reproduce the bug, I don't know if it happened the same way the first time (but it could be very likely) because I wasn't paying attention but here are the steps:

- In Atom, search for "minimap" in Install Packages
- As soon as the search ends, click install on the minimap package

The problem is that you will initially get 4.26.1 as the search result, it will take some seconds for the version message to show up and change the version to 4.25.6. If you click install before that happens 4.26.1 will be installed (the message will still show while installing anyways).
